### ISSUE TITLE
Recall is very low as 0.01% for In-Shop Dataset

### ISSUE THREAD

**Issue by lihyin** [leftthomas/CGD#1]
As shown in the screenshot, the recall is very low as 0.01% for In-Shop Dataset. I have downloaded the dataset at /home/xxx/Documents/CGD/dataset/isc/Img/img/MEN WOMEN . Did I do something wrong?

![Untitled3](https://user-images.githubusercontent.com/1203665/98071441-c9e5cf00-1e20-11eb-81c9-d8f188117b87.png)

**Comment by leftthomas** [comment]
@lihyin you should use the same hyper-parameters as paper said, such as `batch size`

**Comment by enes3774** [comment]
> As shown in the screenshot, the recall is very low as 0.01% for In-Shop Dataset. I have downloaded the dataset at /home/xxx/Documents/CGD/dataset/isc/Img/img/MEN WOMEN . Did I do something wrong?
> 
> ![Untitled3](https://user-images.githubusercontent.com/1203665/98071441-c9e5cf00-1e20-11eb-81c9-d8f188117b87.png)

did you solve the problem?
