### ISSUE TITLE
Nan loss

### ISSUE THREAD

**Issue by nthhiep** [leftthomas/CGD#12]
Hi.  I got an error when running train.py with torch.autograd.detect_anomaly() as follows:
"RuntimeError: Function 'PowBackward0' returned nan values in its 0th output"

This is related to line 27 of model.py. Could you check this please. Thank you for your support.

**Comment by nthhiep** [comment]
Sorry, why did you close my question? I'm using your code and got Nan loss during training. I really hope to get feedback from you. Thank you.

**Comment by leftthomas** [comment]
@nthhiep , Duplicate of  #3
