### ISSUE TITLE
what's the proper prameters  in isc dataset case?

### ISSUE THREAD

**Issue by eksis77** [leftthomas/CGD#13]
i appreciate for  your code!

i am trying to train isc dataset with CGD. 
but, in case of isc dataset,  default parameters and hyper parameters make poor results. 
i used default parameters except batch_size(=32)

following CSV is my results. it dose not be improved each epoch.
please let me know what i am missing.

Thanks~~

epoch,train_loss,train_accuracy,test_recall@1,test_recall@2,test_recall@4,test_recall@8
1,8.402177921616206,0.06961633663366336,0.028133351588621736,0.03516668803058565,0.04923336673527956,0.10550006991252303
2,8.584146980601963,0.050278465346534656,0.29540020041167736,0.45013362541794777,0.8158671669661999,1.5332676470279694
3,8.797435745744423,0.038675742574257425,0.0211000136914663,0.028133351588621736,0.04923336673527956,0.0844000547658652
4,8.711510207983526,0.019337871287128713,0.028133351588621736,0.04923336673527956,0.0703333760611713,0.1406667521223426
5,,0.0270730198019802,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
6,,0.01547029702970297,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
7,,0.0,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
8,,0.01547029702970297,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
9,,0.06188118811881188,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
10,,0.03094059405940594,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
11,,0.03094059405940594,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
12,,0.01547029702970297,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713
13,,0.03094059405940594,0.014066675794310868,0.014066675794310868,0.03516668803058565,0.0703333760611713

**Comment by leftthomas** [comment]
@eksis77 This repo is a reimplement of that paper, so I follow the setting of paper, for the poor results  of other hyper-parameters, you could seek advice from the authors of that paper.
