### ISSUE TITLE
nan during training

### ISSUE THREAD

**Issue by liyuxuan89** [leftthomas/CGD#3]
![image](https://user-images.githubusercontent.com/43963025/104545506-2f4a0d80-5665-11eb-87b1-193f5e0d479b.png)
I trained the network on isc dataset, but the training loss became nan at the very beginning of the training process.

**Comment by liyuxuan89** [comment]
![image](https://user-images.githubusercontent.com/43963025/104554243-e3a05f80-5676-11eb-9e0e-fc5ed49b0770.png)
I change cdist to matmul operation and there appears to be no problem

**Comment by nthhiep** [comment]
Hi.  I got an error when running train.py with torch.autograd.detect_anomaly() as follows:
"RuntimeError: Function 'PowBackward0' returned nan values in its 0th output"

This is related to line 27 of model.py. Could you check this please. Thank you for your support.
