### ISSUE TITLE
model result for sop data

### ISSUE THREAD

**Issue by ruyanyinian** [leftthomas/CGD#7]
I've got an issue that I found out the result of Resnet-50 got 79.3 on SOP dataset, while the orginal paper had 84.3, what happen on this differences? Did you change some hyperparameters, or just ran on 20 epchos which were not enough.

**Comment by leftthomas** [comment]
This is the reimplement code, not official code, the author haven't released the training code, so I didn't know the detail of training, I just according the paper to write this code.
